// Appendix A — PE Rate Types (closed list, v5.6)
// Source: docs/CPS_Contract_Parser.md lines 967-1245

export interface RateTypeRef {
  code: string
  name: string
  minStay: number
  maxStay: number
  minPax: number
  maxPax: number
}

export const APPENDIX_A: RateTypeRef[] = [
  { code: 'PPPD', name: 'Per Person Per Day', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PRPD', name: 'Per Room Per Day', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPS2', name: 'Per Person Per Stay 2 Pax', minStay: 1, maxStay: 99, minPax: 2, maxPax: 2 },
  { code: 'PR', name: 'Per Room', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPN', name: 'Per Person Per Nts', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PRPN', name: 'Per Room Per Nts', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PD', name: 'Per Day', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'NO', name: 'No Calculation', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PUPD', name: 'Per Unit Per Day', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPU', name: 'Per Person Per Unit', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PUPH', name: 'Per Unit Per Hour', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PHPN', name: 'Per House Per Nts', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPN4MIN', name: 'Per Person Per Nts Min 4 Nts', minStay: 4, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPN2N', name: 'Per Person Per Nts Min 2 Nts', minStay: 2, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PUPS', name: 'Per Unit Per Stay', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PUM2D', name: 'Per Unit Per Day Min 2 Day', minStay: 2, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PUPN2', name: 'Per Unit Per Night Min 2 Nts', minStay: 2, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PUPN', name: 'Per Unit Per Nts', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PP1N', name: 'Per Person 1st Night', minStay: 1, maxStay: 1, minPax: 1, maxPax: 99 },
  { code: 'PP2N', name: 'Per Person 2nd Plus Nights', minStay: 2, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PP2P', name: 'PPPN Min 2 Pax', minStay: 1, maxStay: 99, minPax: 2, maxPax: 99 },
  { code: 'PI', name: 'Per Item', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PVPT4', name: 'Per Vehicle Per Transfer 4 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 4 },
  { code: 'PVPT8', name: 'Per Vehicle Per Transfer 8 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 8 },
  { code: 'PV', name: 'Per Vehicle', minStay: 1, maxStay: 99, minPax: 1, maxPax: 6 },
  { code: 'PG', name: 'Per Group', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PVPT6', name: 'Per Vehicle Per Transfer 6 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 6 },
  { code: 'PF2', name: 'EAACPerFlight1-2', minStay: 1, maxStay: 99, minPax: 1, maxPax: 2 },
  { code: 'PF3', name: 'EAACPerFlight3-4', minStay: 1, maxStay: 99, minPax: 3, maxPax: 4 },
  { code: 'PF4', name: 'EAACPerFlight5-8', minStay: 1, maxStay: 99, minPax: 5, maxPax: 8 },
  { code: 'PF5', name: 'EAACPerFlight9-12', minStay: 1, maxStay: 99, minPax: 9, maxPax: 12 },
  { code: 'PF2A', name: 'C182', minStay: 1, maxStay: 99, minPax: 1, maxPax: 2 },
  { code: 'PF3A', name: 'C206', minStay: 1, maxStay: 99, minPax: 1, maxPax: 6 },
  { code: 'PF4A', name: 'C208B', minStay: 1, maxStay: 99, minPax: 1, maxPax: 12 },
  { code: 'PVPT9', name: 'Per Vehicle Per Transfer 9 Pax', minStay: 1, maxStay: 99, minPax: 7, maxPax: 9 },
  { code: 'PVPh', name: 'Per Vehicle Photographic', minStay: 1, maxStay: 99, minPax: 1, maxPax: 6 },
  { code: 'PPPD1', name: 'Per Person Per Day 1 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 1 },
  { code: 'PPPD2', name: 'Per Person Per Day 2 Pax', minStay: 1, maxStay: 99, minPax: 2, maxPax: 2 },
  { code: 'PPPD3', name: 'Per Person Per Day 3 Pax', minStay: 1, maxStay: 99, minPax: 3, maxPax: 3 },
  { code: 'PPPD4', name: 'Per Person Per Day 4 Pax', minStay: 1, maxStay: 99, minPax: 4, maxPax: 4 },
  { code: 'PPPD5', name: 'Per Person Per Day 5 Pax', minStay: 1, maxStay: 99, minPax: 5, maxPax: 5 },
  { code: 'PVPT7', name: 'Per Vehicle Per Transfer 7 Pax', minStay: 1, maxStay: 99, minPax: 5, maxPax: 7 },
  { code: 'PVPT22', name: 'Per Vehicle Per Transfer 22 Pax', minStay: 1, maxStay: 99, minPax: 10, maxPax: 22 },
  { code: 'PP4to6N', name: 'Per Person Per Night 4–6 Nts', minStay: 4, maxStay: 6, minPax: 1, maxPax: 99 },
  { code: 'PP1to3N', name: 'Per Person Per Night 1–3 Nts', minStay: 1, maxStay: 3, minPax: 1, maxPax: 99 },
  { code: 'PP7plusN', name: 'Per Person Per Night Min 7 Nts', minStay: 7, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PRM5N', name: 'Per Room Per Night Min 5 Nts', minStay: 5, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PRM2N', name: 'Per Room Per Night Min 2 Nts', minStay: 2, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPM3', name: 'Per Person Per Night Min 3 Nts', minStay: 3, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPM5N', name: 'Per Person Per Night Min 5 Nts', minStay: 5, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPM6N', name: 'Per Person Per Night Min 6 Nts', minStay: 6, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PRM3N', name: 'Per Room Per Night Min 3 Nts', minStay: 3, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPS', name: 'Per Person Per Stay', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PRM7N', name: 'Per Room Per Night Min 7 Nts', minStay: 7, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PRM4N', name: 'Per Room Per Night Min 4 Nts', minStay: 4, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPD4to8', name: 'Per Person Per Day 4–8 Pax', minStay: 1, maxStay: 99, minPax: 4, maxPax: 8 },
  { code: 'PPPD11', name: 'Per Person Per Day 11+ Pax', minStay: 1, maxStay: 99, minPax: 11, maxPax: 99 },
  { code: 'PPPD9to10', name: 'Per Person Per Day 9 –10 Pax', minStay: 1, maxStay: 99, minPax: 9, maxPax: 10 },
  { code: 'PR1TO2', name: 'Per Room Per Night 1 to 2 Pax Min 3 Nts.', minStay: 3, maxStay: 99, minPax: 1, maxPax: 2 },
  { code: 'PR3P', name: 'Per Room Per Night 3 Pax Min 3 Nts', minStay: 3, maxStay: 99, minPax: 3, maxPax: 3 },
  { code: 'PR4P', name: 'Per Room Per Night 4 Pax Min 3 Nts', minStay: 3, maxStay: 99, minPax: 4, maxPax: 8 },
  { code: 'PR5P', name: 'Per Room Per Night 5 Pax Min 3 Nts', minStay: 3, maxStay: 99, minPax: 5, maxPax: 5 },
  { code: 'PR6P', name: 'Per Room Per Night 6 Pax Min 3 Nts', minStay: 3, maxStay: 99, minPax: 6, maxPax: 6 },
  { code: 'PR7P', name: 'Per Room Per Night 7 Pax Min 3 Nts', minStay: 3, maxStay: 99, minPax: 7, maxPax: 7 },
  { code: 'PR8P', name: 'Per Room Per Night 8 Pax Min 3 Nts', minStay: 3, maxStay: 99, minPax: 8, maxPax: 8 },
  { code: 'PPPNM4', name: 'Per Person Per Night Min 4 Nts', minStay: 4, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PUPN8P', name: 'Per Unit Per Night 8 Pax', minStay: 1, maxStay: 99, minPax: 8, maxPax: 8 },
  { code: 'PUPN1to6', name: 'Per Unit Per Night 1 to 6 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 6 },
  { code: 'PPPN4to8', name: 'Per Person Per Night 4–8 Pax', minStay: 1, maxStay: 99, minPax: 4, maxPax: 8 },
  { code: 'PP4to5N', name: 'Per Person Per Night 4–5 Nts', minStay: 4, maxStay: 5, minPax: 1, maxPax: 99 },
  { code: 'PP6plusN', name: 'Per Person Per Night Min 6 Nts', minStay: 6, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PR1to3N', name: 'Per Room Per Night 1 to 3 Nts', minStay: 1, maxStay: 3, minPax: 1, maxPax: 99 },
  { code: 'PRM6N', name: 'Per Room Per Night Min 6 Nts', minStay: 6, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PR4and5N', name: 'Per Room Per Night 4 and 5 Nts', minStay: 4, maxStay: 5, minPax: 1, maxPax: 99 },
  { code: 'PP1to4N', name: 'Per Person Per Night 1–4 Nts', minStay: 1, maxStay: 4, minPax: 1, maxPax: 99 },
  { code: 'PP5to8N', name: 'Per Person Per Night 5–8 Nts', minStay: 5, maxStay: 8, minPax: 1, maxPax: 99 },
  { code: 'PP9plusN', name: 'Per Person Per Night Min 9 Nts', minStay: 9, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPS1P3N', name: 'Per Person Per Stay 1 Pax 3 Nts', minStay: 3, maxStay: 3, minPax: 1, maxPax: 1 },
  { code: 'PPPS1P4N', name: 'Per Person Per Stay 1 Pax 4 Nts', minStay: 4, maxStay: 4, minPax: 1, maxPax: 1 },
  { code: 'PPPS1P5N', name: 'Per Person Per Stay 1 Pax 5 Nts', minStay: 5, maxStay: 5, minPax: 1, maxPax: 1 },
  { code: 'PPPS1P6N', name: 'Per Person Per Stay 1 Pax 6 Nts', minStay: 6, maxStay: 6, minPax: 1, maxPax: 1 },
  { code: 'PPPS1P7N', name: 'Per Person Per Stay 1 Pax 7 Nts', minStay: 7, maxStay: 7, minPax: 1, maxPax: 1 },
  { code: 'PPPS1P8N', name: 'Per Person Per Stay 1 Pax 8 Nts', minStay: 8, maxStay: 8, minPax: 1, maxPax: 1 },
  { code: 'PPPS1P9N', name: 'Per Person Per Stay 1 Pax 9 Nts', minStay: 9, maxStay: 9, minPax: 1, maxPax: 1 },
  { code: 'PPPS2P3N', name: 'Per Person Per Stay 2 Pax 3 Nights', minStay: 3, maxStay: 3, minPax: 2, maxPax: 2 },
  { code: 'PPPS2P4N', name: 'Per Person Per Stay 2 Pax 4 Nights', minStay: 4, maxStay: 4, minPax: 2, maxPax: 2 },
  { code: 'PPPS2P5N', name: 'Per Person Per Stay 2 Pax 5 Nights', minStay: 5, maxStay: 5, minPax: 2, maxPax: 2 },
  { code: 'PPPS2P6N', name: 'Per Person Per Stay 2 Pax 6 Nights', minStay: 6, maxStay: 6, minPax: 2, maxPax: 2 },
  { code: 'PPPS2P7N', name: 'Per Person Per Stay 2 Pax 7 Nights', minStay: 7, maxStay: 7, minPax: 2, maxPax: 2 },
  { code: 'PPPS2P8N', name: 'Per Person Per Stay 2 Pax 8 Nights', minStay: 8, maxStay: 8, minPax: 2, maxPax: 2 },
  { code: 'PPPS2P9N', name: 'Per Person Per Stay 2 Pax 9 Nights', minStay: 9, maxStay: 9, minPax: 2, maxPax: 2 },
  { code: 'PPPS3P3N', name: 'Per Person Per Stay 3 Pax 3 Nights', minStay: 3, maxStay: 3, minPax: 3, maxPax: 3 },
  { code: 'PPPS3P4N', name: 'Per Person Per Stay 3 Pax 4 Nights', minStay: 4, maxStay: 4, minPax: 3, maxPax: 3 },
  { code: 'PPPS3P5N', name: 'Per Person Per Stay 3 Pax 5 Nights', minStay: 5, maxStay: 5, minPax: 3, maxPax: 3 },
  { code: 'PPPS3P6N', name: 'Per Person Per Stay 3 Pax 6 Nights', minStay: 6, maxStay: 6, minPax: 3, maxPax: 3 },
  { code: 'PPPS3P7N', name: 'Per Person Per Stay 3 Pax 7 Nights', minStay: 7, maxStay: 7, minPax: 3, maxPax: 3 },
  { code: 'PPPS3P8N', name: 'Per Person Per Stay 3 Pax 8 Nights', minStay: 8, maxStay: 8, minPax: 3, maxPax: 3 },
  { code: 'PPPS3P9N', name: 'Per Person Per Stay 3 Pax 9 Nights', minStay: 9, maxStay: 9, minPax: 3, maxPax: 3 },
  { code: 'PPPS4to8P3N', name: 'Per Person Per Stay 4-8 Pax 3 Nights', minStay: 3, maxStay: 3, minPax: 4, maxPax: 8 },
  { code: 'PPPS4to8P4N', name: 'Per Person Per Stay 4-8 Pax 4 Nights', minStay: 4, maxStay: 4, minPax: 4, maxPax: 8 },
  { code: 'PPPS4to8P5N', name: 'Per Person Per Stay 4-8 Pax 5 Nights', minStay: 5, maxStay: 5, minPax: 4, maxPax: 8 },
  { code: 'PPPS4to8P6N', name: 'Per Person Per Stay 4-8 Pax 6 Nights', minStay: 6, maxStay: 6, minPax: 4, maxPax: 8 },
  { code: 'PPPS4to8P7N', name: 'Per Person Per Stay 4-8 Pax 7 Nights', minStay: 7, maxStay: 7, minPax: 4, maxPax: 8 },
  { code: 'PPPS4to8P8N', name: 'Per Person Per Stay 4-8 Pax 8 Nights', minStay: 8, maxStay: 8, minPax: 4, maxPax: 8 },
  { code: 'PPPS4to8P9N', name: 'Per Person Per Stay 4-8 Pax 9 Nights', minStay: 9, maxStay: 9, minPax: 4, maxPax: 8 },
  { code: 'PPPS9to10P3N', name: 'Per Person Per Stay 9-10 Pax 3 Nights', minStay: 3, maxStay: 3, minPax: 9, maxPax: 10 },
  { code: 'PPPS9to10P4N', name: 'Per Person Per Stay 9-10 Pax 4 Nights', minStay: 4, maxStay: 4, minPax: 9, maxPax: 10 },
  { code: 'PPPS9to10P5N', name: 'Per Person Per Stay 9-10 Pax 5 Nights', minStay: 5, maxStay: 5, minPax: 9, maxPax: 10 },
  { code: 'PPPS9to10P6N', name: 'Per Person Per Stay 9-10 Pax 6 Nights', minStay: 6, maxStay: 6, minPax: 9, maxPax: 10 },
  { code: 'PPPS9to10P7N', name: 'Per Person Per Stay 9-10 Pax 7 Nights', minStay: 7, maxStay: 7, minPax: 9, maxPax: 10 },
  { code: 'PPPS9to10P8N', name: 'Per Person Per Stay 9-10 Pax 8 Nights', minStay: 8, maxStay: 8, minPax: 9, maxPax: 10 },
  { code: 'PPPS9to10P9N', name: 'Per Person Per Stay 9-10 Pax 9 Nights', minStay: 9, maxStay: 9, minPax: 9, maxPax: 10 },
  { code: 'PPPS11plusP3N', name: 'Per Person Per Stay 11+ Pax 3 Nts', minStay: 3, maxStay: 3, minPax: 11, maxPax: 99 },
  { code: 'PPPS11plusP4N', name: 'Per Person Per Stay 11+ Pax 4 Nts', minStay: 4, maxStay: 4, minPax: 11, maxPax: 99 },
  { code: 'PPPS11plusP5N', name: 'Per Person Per Stay 11+ Pax 5 Nts', minStay: 5, maxStay: 5, minPax: 11, maxPax: 99 },
  { code: 'PPPS11plusP6N', name: 'Per Person Per Stay 11+ Pax 6 Nts', minStay: 6, maxStay: 6, minPax: 11, maxPax: 99 },
  { code: 'PPPS11plusP7N', name: 'Per Person Per Stay 11+ Pax 7 Nts', minStay: 7, maxStay: 7, minPax: 11, maxPax: 99 },
  { code: 'PPPS11plusP8N', name: 'Per Person Per Stay 11+ Pax 8 Nts', minStay: 8, maxStay: 8, minPax: 11, maxPax: 99 },
  { code: 'PPPS11plusP9N', name: 'Per Person Per Stay 11+ Pax 9 Nts', minStay: 9, maxStay: 9, minPax: 11, maxPax: 99 },
  { code: 'PPPN6P', name: 'Per Person Per Night 6 Pax', minStay: 1, maxStay: 99, minPax: 6, maxPax: 6 },
  { code: 'PPPN8P', name: 'Per Person Per Night 8 Pax', minStay: 1, maxStay: 99, minPax: 8, maxPax: 8 },
  { code: 'PPPN12P', name: 'Per Person Per Night 12 Pax', minStay: 1, maxStay: 99, minPax: 12, maxPax: 12 },
  { code: 'PPPN10P', name: 'Per Person Per Night 10 Pax', minStay: 1, maxStay: 99, minPax: 10, maxPax: 10 },
  { code: 'PPPN3N', name: 'Per Person Per Night Min 3 Nts', minStay: 3, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PRPN1to4N', name: 'Per Room Per Night 1 to 4 Nts', minStay: 1, maxStay: 4, minPax: 1, maxPax: 99 },
  { code: 'PPPN7M', name: 'Per Person Per Night Min 7 Nts', minStay: 7, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPN1P', name: 'Per Person Per Night 1 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 1 },
  { code: 'PPPN2P', name: 'Per Person Per Night 2 Pax', minStay: 1, maxStay: 99, minPax: 2, maxPax: 2 },
  { code: 'PPPN3P', name: 'Per Person Per Night 3 Pax', minStay: 1, maxStay: 99, minPax: 3, maxPax: 3 },
  { code: 'PPPN4P', name: 'Per Person Per Night 4 Pax', minStay: 1, maxStay: 99, minPax: 4, maxPax: 4 },
  { code: 'PPPT2P', name: 'Per Person Per Transfer 2 Pax', minStay: 1, maxStay: 99, minPax: 2, maxPax: 2 },
  { code: 'PRPN5to8N', name: 'Per Room Per Night 5 to 8 Nts', minStay: 5, maxStay: 8, minPax: 1, maxPax: 99 },
  { code: 'PPPN5P', name: 'Per Person Per Night 5 Pax', minStay: 1, maxStay: 99, minPax: 5, maxPax: 5 },
  { code: 'PPPT3to6P', name: 'Per Person Per Transfer 3 to 6 Pax', minStay: 1, maxStay: 99, minPax: 3, maxPax: 6 },
  { code: 'PHPN6P', name: 'Per House Per Night 6 Pax', minStay: 1, maxStay: 99, minPax: 6, maxPax: 12 },
  { code: 'PPPN7P', name: 'Per Person Per Night 7 Pax', minStay: 1, maxStay: 99, minPax: 7, maxPax: 7 },
  { code: 'PPPN9P', name: 'Per Person Per Night 9 Pax', minStay: 1, maxStay: 99, minPax: 9, maxPax: 9 },
  { code: 'PUPN6P', name: 'Per Unit Per Night 6 Pax', minStay: 1, maxStay: 99, minPax: 6, maxPax: 6 },
  { code: 'PHP7N', name: 'Per House Per Stay 7 Nts', minStay: 7, maxStay: 7, minPax: 1, maxPax: 8 },
  { code: 'PPPS43N', name: 'Per Person Per Stay 4 Pax 3 Nights', minStay: 3, maxStay: 3, minPax: 4, maxPax: 4 },
  { code: 'PPPS53N', name: 'Per Person Per Stay 5 Pax 3 Nights', minStay: 3, maxStay: 3, minPax: 5, maxPax: 5 },
  { code: 'PPPS63N', name: 'Per Person Per Stay 6 Pax 3 Nights', minStay: 3, maxStay: 3, minPax: 6, maxPax: 6 },
  { code: 'PPPS73N', name: 'Per Person Per Stay 7 Pax 3 Nights', minStay: 3, maxStay: 3, minPax: 7, maxPax: 7 },
  { code: 'PPPS8plus3N', name: 'Per Person Per Stay 8+ Pax 3 Nights', minStay: 3, maxStay: 3, minPax: 8, maxPax: 99 },
  { code: 'PPPS4P4N', name: 'Per Person Per Stay 4 Pax 4 Nights', minStay: 4, maxStay: 4, minPax: 4, maxPax: 4 },
  { code: 'PPPS5P4N', name: 'Per Person Per Stay 5 Pax 4 Nights', minStay: 4, maxStay: 4, minPax: 5, maxPax: 5 },
  { code: 'PPPS6P4N', name: 'Per Person Per Stay 6 Pax 4 Nights', minStay: 4, maxStay: 4, minPax: 6, maxPax: 6 },
  { code: 'PPPS7P4N', name: 'Per Person Per Stay 7 Pax 4 Nights', minStay: 4, maxStay: 4, minPax: 7, maxPax: 7 },
  { code: 'PPPS8plus4N', name: 'Per Person Per Stay 8+ Pax 4 Nights', minStay: 4, maxStay: 4, minPax: 8, maxPax: 99 },
  { code: 'PPPS4P5N', name: 'Per Person Per Stay 4 Pax 5 Nights', minStay: 5, maxStay: 5, minPax: 4, maxPax: 4 },
  { code: 'PPPS5P5N', name: 'Per Person Per Stay 5 Pax 5 Nights', minStay: 5, maxStay: 5, minPax: 5, maxPax: 5 },
  { code: 'PPPS6P5N', name: 'Per Person Per Stay 6 Pax 5 Nights', minStay: 5, maxStay: 5, minPax: 6, maxPax: 6 },
  { code: 'PPPS7P5N', name: 'Per Person Per Stay 7 Pax 5 Nights', minStay: 5, maxStay: 5, minPax: 7, maxPax: 7 },
  { code: 'PPPS8plus5N', name: 'Per Person Per Stay 8+ Pax 5 Nights', minStay: 5, maxStay: 5, minPax: 8, maxPax: 99 },
  { code: 'PVPT12', name: 'Per Vehicle Per Transfer 12 Pax', minStay: 1, maxStay: 99, minPax: 6, maxPax: 12 },
  { code: 'PUPN12P', name: 'Per Unit Per Night 12 Pax', minStay: 1, maxStay: 99, minPax: 12, maxPax: 12 },
  { code: 'PUPN10P', name: 'Per Unit Per Night 10 Pax', minStay: 1, maxStay: 99, minPax: 10, maxPax: 10 },
  { code: 'PPPS12N', name: 'Per Person Per Stay 12 Nts', minStay: 12, maxStay: 12, minPax: 1, maxPax: 99 },
  { code: 'PUPN2P', name: 'Per Unit Per Night 2 Pax', minStay: 1, maxStay: 99, minPax: 2, maxPax: 2 },
  { code: 'PUPN3P', name: 'Per Unit Per Night 3 Pax', minStay: 1, maxStay: 99, minPax: 3, maxPax: 3 },
  { code: 'PUPN4P', name: 'Per Unit Per Night 4 Pax', minStay: 1, maxStay: 99, minPax: 4, maxPax: 4 },
  { code: 'PUPN5P', name: 'Per Unit Per Night 5 Pax', minStay: 1, maxStay: 99, minPax: 5, maxPax: 5 },
  { code: 'PUPN7P', name: 'Per Unit Per Night 7 Pax', minStay: 1, maxStay: 99, minPax: 7, maxPax: 7 },
  { code: 'PHPN1to4', name: 'Per House Per Night 1–4 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 4 },
  { code: 'PPPN5to8P', name: 'Per Person Per Night 5–8 Pax', minStay: 1, maxStay: 99, minPax: 5, maxPax: 8 },
  { code: 'PPPN9to12P', name: 'Per Person Per Nt 9–12 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPN13P', name: 'Per Person Per Nt 13+ Pax', minStay: 1, maxStay: 99, minPax: 13, maxPax: 99 },
  { code: 'PPPS9N', name: 'Per Person Per Stay 9 Nts', minStay: 9, maxStay: 9, minPax: 1, maxPax: 99 },
  { code: 'PS2P9N', name: 'Per Stay 2 Pax 9 Nts', minStay: 9, maxStay: 9, minPax: 2, maxPax: 2 },
  { code: 'PS3P9N', name: 'Per Stay 3 Pax 9 Nts', minStay: 9, maxStay: 9, minPax: 3, maxPax: 3 },
  { code: 'PS4P9N', name: 'Per Stay 4 Pax 9 Nts', minStay: 9, maxStay: 9, minPax: 4, maxPax: 4 },
  { code: 'PS5P9N', name: 'Per Stay 5 Pax 9 Nts', minStay: 9, maxStay: 9, minPax: 5, maxPax: 5 },
  { code: 'PS6P9N', name: 'Per Stay 6 Pax 9 Nts', minStay: 9, maxStay: 9, minPax: 6, maxPax: 6 },
  { code: 'PS7P9N', name: 'Per Stay 7 Pax 9 Nts', minStay: 9, maxStay: 9, minPax: 7, maxPax: 7 },
  { code: 'PS8P9N', name: 'Per Stay 8 Pax 9 Nts', minStay: 9, maxStay: 9, minPax: 8, maxPax: 8 },
  { code: 'PPPN5plusP', name: 'Per Person Per Nt 5+ Pax', minStay: 1, maxStay: 99, minPax: 5, maxPax: 99 },
  { code: 'PS2P12N', name: 'Per Stay 2 Pax 12 Nts', minStay: 12, maxStay: 12, minPax: 2, maxPax: 2 },
  { code: 'PS3P12N', name: 'Per Stay 3 Pax 12 Nts', minStay: 12, maxStay: 12, minPax: 3, maxPax: 3 },
  { code: 'PS4P12N', name: 'Per Stay 4 Pax 12 Nts', minStay: 12, maxStay: 12, minPax: 4, maxPax: 4 },
  { code: 'PS5P12N', name: 'Per Stay 5 Pax 12 Nts', minStay: 12, maxStay: 12, minPax: 5, maxPax: 5 },
  { code: 'PS6P12N', name: 'Per Stay 6 Pax 12 Nts', minStay: 12, maxStay: 12, minPax: 6, maxPax: 6 },
  { code: 'PS7P12N', name: 'Per Stay 7 Pax 12 Nts', minStay: 12, maxStay: 12, minPax: 7, maxPax: 7 },
  { code: 'PS8P12N', name: 'Per Stay 8 Pax 12 Nts', minStay: 12, maxStay: 12, minPax: 8, maxPax: 8 },
  { code: 'PRPN4to6N', name: 'Per Room Per Nt 4 to 6 Nts', minStay: 4, maxStay: 6, minPax: 1, maxPax: 99 },
  { code: 'PPPN1to4P', name: 'Per Person Per Night 1–4 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 4 },
  { code: 'PPPS7N', name: 'Per Person Per Stay 7 Nts', minStay: 7, maxStay: 7, minPax: 1, maxPax: 99 },
  { code: 'PGPN', name: 'Per Group Per Night', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PP1D', name: 'Per Person First Day', minStay: 1, maxStay: 1, minPax: 1, maxPax: 99 },
  { code: 'PP2D', name: 'Per Person Second Days', minStay: 2, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPD2P', name: 'Per Person Per Day 2+ Pax', minStay: 1, maxStay: 99, minPax: 2, maxPax: 99 },
  { code: 'PPPI', name: 'Per Person Per Item', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PUPN5N', name: 'Per Unit Per Night Min 5 Nts', minStay: 5, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPN3plusP', name: 'Per Person Per Night 3+ Pax', minStay: 1, maxStay: 99, minPax: 3, maxPax: 99 },
  { code: 'PPPWD', name: 'Per Person Per Whole Duration', minStay: 1, maxStay: 30, minPax: 1, maxPax: 999 },
  { code: 'PPPS3plus3N', name: 'Per Person Per Stay 3+Pax 3 Nights', minStay: 3, maxStay: 3, minPax: 3, maxPax: 99 },
  { code: 'PS2P7N', name: 'Per Stay 2 Pax 7 Nts', minStay: 7, maxStay: 7, minPax: 2, maxPax: 2 },
  { code: 'PS3P7N', name: 'Per Stay 3 Pax 7 Nts', minStay: 7, maxStay: 7, minPax: 3, maxPax: 3 },
  { code: 'PS4P7N', name: 'Per Stay 4 Pax 7 Nts', minStay: 7, maxStay: 7, minPax: 4, maxPax: 4 },
  { code: 'PS5P7N', name: 'Per Stay 5 Pax 7 Nts', minStay: 7, maxStay: 7, minPax: 5, maxPax: 5 },
  { code: 'PS6P7N', name: 'Per Stay 6 Pax 7 Nts', minStay: 7, maxStay: 7, minPax: 6, maxPax: 6 },
  { code: 'PS7P7N', name: 'Per Stay 7 Pax 7 Nts', minStay: 7, maxStay: 7, minPax: 7, maxPax: 7 },
  { code: 'PS8P7N', name: 'Per Stay 8 Pax 7 Nts', minStay: 7, maxStay: 7, minPax: 8, maxPax: 8 },
  { code: 'PPPD7P', name: 'Per Person Per Day 7+ Pax', minStay: 1, maxStay: 99, minPax: 7, maxPax: 99 },
  { code: 'PPPD6', name: 'Per Person Per Day 6 Pax', minStay: 1, maxStay: 99, minPax: 6, maxPax: 6 },
  { code: 'PPPD4to6', name: 'Per Person Per Day 4–6 Pax', minStay: 1, maxStay: 99, minPax: 4, maxPax: 6 },
  { code: 'PUPD1to8P', name: 'Per Unit Per Day 1 to 8 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 8 },
  { code: 'PPPS4P6N', name: 'Per Person Per Stay 4 Pax 6 Nights', minStay: 6, maxStay: 6, minPax: 4, maxPax: 4 },
  { code: 'PPPS6P6N', name: 'Per Person Per Stay 6 Pax 6 Nights', minStay: 6, maxStay: 6, minPax: 6, maxPax: 6 },
  { code: 'PPPD4to9', name: 'Per Person Per Day 4-9 Pax', minStay: 1, maxStay: 99, minPax: 4, maxPax: 9 },
  { code: 'PPPD10P', name: 'Per Person Per Day 10+ Pax', minStay: 1, maxStay: 99, minPax: 10, maxPax: 99 },
  { code: 'PPPS4P7N', name: 'Per Person Per Stay 4 Pax 7 Nights', minStay: 7, maxStay: 7, minPax: 4, maxPax: 4 },
  { code: 'PPPS6P7N', name: 'Per Person Per Stay 6 Pax 7 Nights', minStay: 7, maxStay: 7, minPax: 6, maxPax: 6 },
  { code: 'PP5Pax', name: 'Per Person 5 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PUPD9to12P', name: 'Per Unit Per Day 9 to 12 Pax', minStay: 1, maxStay: 99, minPax: 9, maxPax: 12 },
  { code: 'PUPD13to16P', name: 'Per Unit Per Day 13 to 16 Pax', minStay: 1, maxStay: 99, minPax: 13, maxPax: 16 },
  { code: 'PPPD6P', name: 'Per Person Per Day 6+ Pax', minStay: 1, maxStay: 99, minPax: 6, maxPax: 99 },
  { code: 'PPPS1P', name: 'Per Person Per Stay 1 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 1 },
  { code: 'PPPS3P', name: 'Per Person Per Stay 3 Pax', minStay: 1, maxStay: 99, minPax: 3, maxPax: 3 },
  { code: 'PPPS4P', name: 'Per Person Per Stay 4 Pax', minStay: 1, maxStay: 99, minPax: 4, maxPax: 4 },
  { code: 'PPPS5P', name: 'Per Person Per Stay 5 Pax', minStay: 1, maxStay: 99, minPax: 5, maxPax: 5 },
  { code: 'PPPS6P', name: 'Per Person Per Stay 6 Pax', minStay: 1, maxStay: 99, minPax: 6, maxPax: 6 },
  { code: 'PPPS7P', name: 'Per Person Per Stay 7 Pax', minStay: 1, maxStay: 99, minPax: 7, maxPax: 7 },
  { code: 'PPPS8plusP', name: 'Per Person Per Stay 8+ Pax', minStay: 1, maxStay: 99, minPax: 8, maxPax: 99 },
  { code: 'PPPN8PlusN', name: 'Per Person Per Night Min 8 Nts', minStay: 8, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPD1to5P', name: 'Per Person Per Day 1 to 5 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 5 },
  { code: 'PPPD6to15P', name: 'Per Person Per Day 6 to15 Pax', minStay: 1, maxStay: 99, minPax: 6, maxPax: 15 },
  { code: 'PPPD16P', name: 'Per Person Per Day 16+ Pax', minStay: 1, maxStay: 99, minPax: 16, maxPax: 99 },
  { code: 'PGPD', name: 'Per Group Per Day', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PUPN7plusP', name: 'Per Unit Per Night 7+ Pax', minStay: 1, maxStay: 99, minPax: 7, maxPax: 99 },
  { code: 'PUPN1P', name: 'Per Unit Per Night 1 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 1 },
  { code: 'PP1Pax', name: 'Per Person 1 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PP2Pax', name: 'Per Person 2 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PP3Pax', name: 'Per Person 3 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PP4Pax', name: 'Per Person 4 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PP6Pax', name: 'Per Person 6 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PRPN1to2P', name: 'Per Room Per Night 1 to 2 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 2 },
  { code: 'PRPN3to4P', name: 'Per Room Per Night 3 to 4 Pax', minStay: 1, maxStay: 99, minPax: 3, maxPax: 4 },
  { code: 'PRPN1to4P', name: 'Per Room Per Night 1 to 4 Pax', minStay: 1, maxStay: 99, minPax: 1, maxPax: 4 },
  { code: 'PRPN5to8P', name: 'Per Room Per Night 5 to 8 Pax', minStay: 1, maxStay: 99, minPax: 5, maxPax: 8 },
  { code: 'PVPT14', name: 'Per Vehicle Per Transfer 14 Pax', minStay: 1, maxStay: 99, minPax: 7, maxPax: 14 },
  { code: 'PVPT5', name: 'Per Vehicle Per Transfer 5 to 8 Pax', minStay: 1, maxStay: 99, minPax: 5, maxPax: 8 },
  { code: 'PVPT15', name: 'Per Vehicle Per Transfer 15 Pax', minStay: 1, maxStay: 99, minPax: 8, maxPax: 15 },
  { code: 'PRPN5to6P', name: 'Per Room Per Night 5 to 6 Pax', minStay: 1, maxStay: 99, minPax: 5, maxPax: 6 },
  { code: 'PRPN7to8P', name: 'Per Room Per Night 7 to 8 Pax', minStay: 1, maxStay: 99, minPax: 7, maxPax: 8 },
  { code: 'PPPS11N', name: 'Per Person Per Stay 11 Nts', minStay: 11, maxStay: 11, minPax: 1, maxPax: 99 },
  { code: 'PRPN9+N', name: 'Per Room Per Night 9+ Nts', minStay: 9, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PPPS1P10N', name: 'Per Person Per Stay 1 Pax 10 Nights', minStay: 10, maxStay: 10, minPax: 1, maxPax: 1 },
  { code: 'PPPS2P10N', name: 'Per Person Per Stay 2 Pax 10 Nights', minStay: 10, maxStay: 10, minPax: 2, maxPax: 2 },
  { code: 'PPPS3P10N', name: 'Per Person Per Stay 3 Pax 10 Nights', minStay: 10, maxStay: 10, minPax: 3, maxPax: 3 },
  { code: 'PPPS4to8P10N', name: 'Per Person Per Stay 4-8 Pax 10 Nights', minStay: 10, maxStay: 10, minPax: 4, maxPax: 8 },
  { code: 'PPPS9to10P10N', name: 'Per Person Per Stay 9-10 Pax 10 Nights', minStay: 10, maxStay: 10, minPax: 9, maxPax: 10 },
  { code: 'PPPS11plusP10N', name: 'Per Person Per Stay 11+ Pax 10 Nights', minStay: 10, maxStay: 10, minPax: 11, maxPax: 99 },
  { code: 'PPPS1P2N', name: 'Per Person Per Stay 1 Pax 2 Nights', minStay: 2, maxStay: 2, minPax: 1, maxPax: 1 },
  { code: 'PPPS2P2N', name: 'Per Person Per Stay 2 Pax 2 Nights', minStay: 2, maxStay: 2, minPax: 2, maxPax: 2 },
  { code: 'PPPS3P2N', name: 'Per Person Per Stay 3 Pax 2 Nights', minStay: 2, maxStay: 2, minPax: 3, maxPax: 3 },
  { code: 'PPPS4to8P2N', name: 'Per Person Per Stay 4-8 Pax 2 Nights', minStay: 2, maxStay: 2, minPax: 4, maxPax: 8 },
  { code: 'PPPS9to10P2N', name: 'Per Person Per Stay 9-10 Pax 2 Nights', minStay: 2, maxStay: 2, minPax: 9, maxPax: 10 },
  { code: 'PPPS11plusP2N', name: 'Per Person Per Stay 11+ Pax 2 Nights', minStay: 2, maxStay: 2, minPax: 11, maxPax: 99 },
  { code: 'PPPS5P7N', name: 'Per Person Per Stay 5 Pax 7 Nights', minStay: 7, maxStay: 7, minPax: 5, maxPax: 5 },
  { code: 'PPPS7P7N', name: 'Per Person Per Stay 7 Pax 7 Nights', minStay: 7, maxStay: 7, minPax: 7, maxPax: 7 },
  { code: 'PPPS8P7N', name: 'Per Person Per Stay 8 Pax 7 Nights', minStay: 7, maxStay: 7, minPax: 8, maxPax: 8 },
  { code: 'PUPD6D', name: 'Per Unit Per Day 6 Days', minStay: 1, maxStay: 6, minPax: 1, maxPax: 99 },
  { code: 'PUPD7D', name: 'Per Unit Per Day 7 Plus Days', minStay: 7, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PGPS', name: 'Per Group Per Stay', minStay: 99, maxStay: 99, minPax: 1, maxPax: 99 },
  { code: 'PHPN5P', name: 'Per House Per Night 5 Pax', minStay: 1, maxStay: 99, minPax: 5, maxPax: 5 },
  { code: 'PUPN9P', name: 'Per Unit Per Night 9 Pax', minStay: 1, maxStay: 99, minPax: 9, maxPax: 9 },
  { code: 'PUPN11P', name: 'Per Unit Per Night 11 Pax', minStay: 1, maxStay: 99, minPax: 11, maxPax: 11 },
  { code: 'PPPS4P9N', name: 'Per Person Per Stay 4 Pax 9 Nights', minStay: 9, maxStay: 9, minPax: 4, maxPax: 4 },
  { code: 'PPPS5P9N', name: 'Per Person Per Stay 5 Pax 9 Nights', minStay: 9, maxStay: 9, minPax: 5, maxPax: 5 },
  { code: 'PPPS6P9N', name: 'Per Person Per Stay 6 Pax 9 Nights', minStay: 9, maxStay: 9, minPax: 6, maxPax: 6 },
  { code: 'PPPS7P9N', name: 'Per Person Per Stay 7 Pax 9 Nights', minStay: 9, maxStay: 9, minPax: 7, maxPax: 7 },
  { code: 'PPPS8P9N', name: 'Per Person Per Stay 8 Pax 9 Nights', minStay: 9, maxStay: 9, minPax: 8, maxPax: 8 },
  { code: 'PPPS2P12N', name: 'Per Person Per Stay 2 Pax 12 Nights', minStay: 12, maxStay: 12, minPax: 2, maxPax: 2 },
  { code: 'PPPS3P12N', name: 'Per Person Per Stay 3 Pax 12 Nights', minStay: 12, maxStay: 12, minPax: 3, maxPax: 3 },
  { code: 'PPPS4P12N', name: 'Per Person Per Stay 4 Pax 12 Nights', minStay: 12, maxStay: 12, minPax: 4, maxPax: 4 },
  { code: 'PPPS5P12N', name: 'Per Person Per Stay 5 Pax 12 Nights', minStay: 12, maxStay: 12, minPax: 5, maxPax: 5 },
  { code: 'PPPS6P12N', name: 'Per Person Per Stay 6 Pax 12 Nights', minStay: 12, maxStay: 12, minPax: 6, maxPax: 6 },
  { code: 'PPPS7P12N', name: 'Per Person Per Stay 7 Pax 12 Nights', minStay: 12, maxStay: 12, minPax: 7, maxPax: 7 },
  { code: 'PPPS8P12N', name: 'Per Person Per Stay 8 Pax 12 Nights', minStay: 12, maxStay: 12, minPax: 8, maxPax: 8 },
]

export const APPENDIX_A_MAP = new Map<string, RateTypeRef>(
  APPENDIX_A.map((r) => [r.code, r]),
)

export function lookupRateType(code: string): RateTypeRef | undefined {
  return APPENDIX_A_MAP.get(code.toUpperCase())
}

export function isValidRateTypeCode(code: string): boolean {
  return APPENDIX_A_MAP.has(code.toUpperCase())
}
